version: '3.8'

services:
  frank:
    build: .
    image: ghcr.io/wearefrank/frankframework-demo:${VERSION:-main}
    ports:
      - "${PORT:-8080}:8080"
    environment:
      TZ: ${TIME_ZONE:-Europe/Amsterdam}
    env_file:
      - .env
    volumes:
      - ${SECRETS_PATH:-./src/main/secrets}:/opt/frank/secrets
    restart: unless-stopped

