<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.wearefrank.frankframework.demo</groupId>
    <artifactId>frankframework-demo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <repositories>
        <repository>
            <id>frankframework</id>
            <url>https://nexus.frankframework.org/content/groups/public</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.frankframework</groupId>
            <artifactId>frank-flow</artifactId>
            <version>[3,)</version>
            <type>war</type>
            <exclusions>
                <!--
                Prevent CI/CD failure because of missing FF 8.2.0-20240611.042327. GitHub Actions 20260920:
                #13 50.92 [ERROR] Failed to read artifact descriptor for org.frankframework:frank-flow:war:3.0.0-20240611.160433
                #13 50.92 [ERROR] 	Caused by: The following artifacts could not be resolved: org.frankframework:frankframework-parent:pom:8.2.0-20240611.042327 (absent): Could not find artifact org.frankframework:frankframework-parent:pom:8.2.0-20240611.042327 in frankframework (https://nexus.frankframework.org/content/groups/public)
                -->
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.0</version>
                <executions>
                    <execution>
                        <id>unpack-frank-flow</id>
                        <phase>package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeArtifactIds>frank-flow</includeArtifactIds>
                            <outputDirectory>${project.build.directory}/frank-flow-webapp</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
